INSERT INTO TBL_STUDENT (COURSE, NAME) VALUES ('Direito', 'Harrier Du Bois');
INSERT INTO TBL_STUDENT (COURSE, NAME) VALUES ('Direito', 'Kim Katsuragi');
INSERT INTO TBL_STUDENT (COURSE, NAME) VALUES ('Artes', 'Ruby');